name: katallaxie

nextApp:
  component: "@sls-next/serverless-component@1.19.0-alpha.40"
  inputs:
    memory: 1024
    domain: ["katallaxie.me"]
    cloudfront:
      aliases: ["katallaxie.dev", "www.katallaxie.dev"]
